In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('metadata.csv')
df

,Unnamed: 0,video,start,end,subtitle,include
0,0,IuVo4fnpLC8,"00:09:59,790","00:10:02,100",impacts of privatization small,True
1,1,IuVo4fnpLC8,"00:02:45,390","00:02:48,569",sacrificial holy that is a dark,True
2,2,IuVo4fnpLC8,"00:14:02,399","00:14:04,560",to unveil a postal service themed,True
3,3,IuVo4fnpLC8,"00:14:20,389","00:14:23,459",I'm gonna give it a three and a half out,False
4,4,IuVo4fnpLC8,"00:17:07,709","00:17:11,069",buy right now if you go to stamps com,True
...,...,...,...,...,...,...
18208,18208,IuVo4fnpLC8,"00:05:47,947","00:05:49,248",I put a ban on China.,False
18209,18209,IuVo4fnpLC8,"00:04:06,779","00:04:09,715","Also, Kumail Nanjiani's gonna get really jacke...",True
18210,18210,IuVo4fnpLC8,"00:06:06,665","00:06:09,034",and we're all very lucky he did.,True
18211,18211,IuVo4fnpLC8,"00:00:30,596","00:00:32,098",they don't talk about it.,False
18212,18212,IuVo4fnpLC8,"00:13:40,251","00:13:42,754",the severity and spread of the virus.,False